### PR TITLE
Add status message handling to GET and POST Requests

### PR DESCRIPTION
**Pull request by tysontrail**
# launchDarklyController.js
- Added status message handling to throw error and send message recieved from Launch Darkly API if 200 status code isn't recieved

### CODE REVIEW

**Review by kWeech — CHANGES_REQUESTED** [review]
Excellent error catching Tyson. Does it still work with !== for best practice?

**Comment by tysontrail** [comment]
Good feedback, updated the status code logic.

**Review by tysontrail — COMMENTED** [review]
Good feedback

**Review by kWeech — APPROVED** [review]
Nice change. Glad it worked.

**Pull request merged**
